---
 - name: Assign hostnames
   hostname: name={{ hostname }}
 - name: Change hosts
   lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1(\s)*\S*\.sciion\.me' line='127.0.0.1 {{ hostname }}.sciion.me {{ hostname}}'
