---
 - name: Assign hostnames
   hostname: name={{ hostname }}
 - name: Change hosts file to new hostname
   lineinfile: dest=/etc/hosts regexp='127.0.1.1\s*(\w+)' line='127.0.1.1 {{ hostname }}.{{ domain }} {{ hostname }}' 


