---
 - name: Download unattended package
   action: apt name={{item}} state=installed
   with_items:
       - "unattended-upgrades"
       - "apt-listchanges"
       - "needrestart"
 - name: Set 50unattended
   template: src="unattended.j2" dest="/etc/apt/apt.conf.d/50unattended-upgrades"
   when: ansible_os_family == "Debian"
 - name: Set 02periodic
   template: src="periodic.j2" dest="/etc/apt/apt.conf.d/02periodic"
   when: ansible_os_family == "Debian"