# Assumes a ssh server is active on guest.
# Set public keys to users defined in the vault file.
---
 - name: Include sshd_config vars
   include_vars: sshd_config.yml
 - name: Stop sshd
   service: name=sshd state=stopped enabled=yes

 - name: Remove old host files
   file: path=/etc/ssh/ssh_host_* state=absent

 - name: Reconfigure openssh-server
   command: dpkg-reconfigure openssh-server

 - name:  Start sshd
   service: name=sshd state=started enabled=yes

 - name: Create .ssh dir
   file: path="/home/{{ item.name }}/.ssh" state=directory owner="{{ item.name }}" group="{{ item.name }}"
   with_items: "{{ users }}"
   when: users is defined

 - name: Set authorized_keys
   authorized_key: user="{{ item.name }}" key="{{ item.pubkey }}"
   with_items: "{{ users }}"
   when: users is defined

 - name: Set permit root login to {{ allow_root }}
   lineinfile: 
     dest=/etc/ssh/sshd_config 
     regexp='^PermitRootLogin' 
     line='PermitRootLogin {{ allow_root }}'

 - name: Set port to {{ port }}
   lineinfile: 
      dest=/etc/ssh/sshd_config 
      regexp='^Port' 
      line='Port {{ port }}' 
 
 - name: Set password authentication to {{ allow_password }}
   lineinfile: 
     dest=/etc/ssh/sshd_config
     regexp="^PasswordAuthentication"
     line="PasswordAuthentication {{ allow_password }}"
     state=present
   notify:
    - restart sshd